### ISSUE TITLE
codegen issue

### ISSUE THREAD

**Issue by amantiwari1** [correttojs/graphql-codegen-apollo-next-ssr#186]
```yaml
overwrite: true
schema: "http://localhost:1337/graphql"
documents: "graphql/**/*.graphql"
generates:
  generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      reactApolloVersion: 3
      withHooks: false
      withHOC: false
      withComponent: false
      exportFragmentSpreadSubTypes: true
      documentMode: graphQLTag
  generated/page.tsx:
    config:
      documentMode: external
      importDocumentNodeExternallyFrom: ./graphql
      reactApolloVersion: 3
      withHooks: true
      # withHOC: false
      # excludePatterns: 'getComments'
      # excludePatternsOptions: 'i'
      # customDataIdFromObjectName: 'test'
      # customDataIdFromObjectImport: 'abc'
      apolloClientInstanceImport: "@withApollo"
      # apolloStateKey: '__APOLLO_STATE__'
    preset: import-types
    presetConfig:
      typesPath: ./graphql
    plugins:
      - "graphql-codegen-apollo-next-ssr/build/src/index.js" # replace by - graphql-codegen-apollo-next-ssr

```
```shell
 generated/page.tsx
    Unable to find preset matching 'import-types'
    Install one of the following packages:


    - @graphql-codegen/import-types
    - @graphql-codegen/import-types-preset
    - import-types
    Error: Unable to find preset matching import-types
        at getPresetByName (/home/aman/Work/ew_work1/client/node_modules/@graphql-codegen/cli/bin.js:404:11)
        at async /home/aman/Work/ew_work1/client/node_modules/@graphql-codegen/cli/bin.js:932:47
        at async Task.task (/home/aman/Work/ew_work1/client/node_modules/@graphql-codegen/cli/bin.js:760:17)
    Error: Unable to find preset matching import-types
        at getPresetByName (/home/aman/Work/ew_work1/client/node_modules/@graphql-codegen/cli/bin.js:404:11)
        at async /home/aman/Work/ew_work1/client/node_modules/@graphql-codegen/cli/bin.js:932:47
        at async Task.task (/home/aman/Work/ew_work1/client/node_modules/@graphql-codegen/cli/bin.js:760:17)
```
