### ISSUE TITLE
Allow setting `near-operation-file` file extension

### ISSUE THREAD

**Issue by rohit-gohri** [correttojs/graphql-codegen-apollo-next-ssr#289]
I'm using the `near-operation-file` preset to generate the base types, and would like to keep them that way. My config `.graphqlrc.yml` looks like this:

```yaml
schema: '${GRAPHQL_SERVER:http://localhost:3000/graphql}'
extensions:
  codegen:
    watch: true
    overwrite: true
    generates:
      packages/types/src/graphql.ts:
        plugins:
          - add
          - 'typescript'

      apps/web-app/gql:
        documents:
          - 'apps/web-app/src/**/*.graphql'
        preset: near-operation-file
        presetConfig:
          extension: .generated.ts
          baseTypesPath: '~@pkg/types/graphql'
        plugins:
          - 'typescript-operations'
          - 'typescript-react-apollo'
        config:
          withHooks: false
          reactApolloVersion: 3

      apps/web-app/next:
        documents:
          - 'apps/web-app/src/**/*.graphql'
        preset: near-operation-file
        presetConfig:
          extension: .page.tsx
          baseTypesPath: '~@pkg/types/graphql'
        plugins:
          - 'apollo-next-ssr'
        config:
          documentMode: external
          importDocumentNodeExternallyFrom: near-operation-file
          withHooks: true
          contextType: 'ApolloClientContext'
          contextTypeRequired: true
          apolloClientInstanceImport: '~/utils/apollo/client'
          reactApolloVersion: 3
```

Types are generated in `.generated.ts` files and not `.graphql` files. Would it be possible to provide a suffix for `importDocumentNodeExternallyFrom: near-operation-file` option?
