### ISSUE TITLE
Getting error `TypeError: visitFn.call is not a function`

### ISSUE THREAD

**Issue by austonpramodh** [correttojs/graphql-codegen-apollo-next-ssr#321]
![image](https://user-images.githubusercontent.com/5049050/140791756-ec4c4bd5-dd04-4f21-8741-622d9c4bc1d6.png)

##### Dependencies:
    "@graphql-codegen/cli": "^2.2.2",
    "@graphql-codegen/import-types-preset": "^2.1.7",
    "@graphql-codegen/typescript": "^2.3.1",
    "@graphql-codegen/typescript-operations": "^2.2.0",
    "@graphql-codegen/typescript-react-apollo": "^3.2.1",
    "graphql-codegen-apollo-next-ssr": "^1.7.1"

##### Codegen file
```yaml
overwrite: true
schema: "https://countries.trevorblades.com/"
# documents: "src/**/*.graphql"
generates:
  src/generated/graphql.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      reactApolloVersion: 3
      withHooks: false
      withHOC: false
      withComponent: false
      exportFragmentSpreadSubTypes: true
      documentMode: graphQLTag
  src/generated/page.tsx:
    config:
      documentMode: external
      importDocumentNodeExternallyFrom: ./graphql
      reactApolloVersion: 3
      withHooks: true
      contextType: "ApolloClientContext"
      contextTypeRequired: true
      # withHOC: false
      # excludePatterns: 'getComments'
      # excludePatternsOptions: 'i'
      # customDataIdFromObjectName: 'test'
      # customDataIdFromObjectImport: 'abc'
      apolloClientInstanceImport: "../withApollo"
      # apolloStateKey: '__APOLLO_STATE__'
    preset: import-types
    presetConfig:
      typesPath: ./graphql
    plugins:
      # - "./build/src/index.js" # replace by - graphql-codegen-apollo-next-ssr
      - graphql-codegen-apollo-next-ssr
```

I am thinking its a issue due to the dependencies, I tried running example and it worked completely fine.

I will try upgrading each package in example project and see where it breaks, will update here.
