### ISSUE TITLE
Trying it out with apollo client 3.0, missing `NormalizedCacheObject`

### ISSUE THREAD

**Issue by paales** [correttojs/graphql-codegen-apollo-next-ssr#5]
Hi there, this seems like an awesome module and was specifically what I was looking for. Great work!

Config:

```
  generated/page.tsx:
    plugins:
      - apollo-next-ssr
    # preset: import-types
    # presetConfig:
    #   typesPath: ./graphql
    config:
      documentMode: external
      importDocumentNodeExternallyFrom: ./apollo.ts
      typesPrefix: GQL
      # reactApolloVersion: 3
      apolloCacheImportFrom: '@apollo/client'
```

The plugin path in the documentation is wrong it is referring to some build path, but it should be `apollo-next-ssr`

It seems I'm missing the type for the NormalizedCacheObject which I would expect to exist here:
`import { QueryHookOptions, useQuery, NormalizedCacheObject } from '@apollo/client'`

Also getting a few errors:
![Schermafbeelding 2020-07-20 om 10 43 36](https://user-images.githubusercontent.com/1244416/87917879-e9293e00-ca75-11ea-9c3e-b206960b1be6.png)

![Schermafbeelding 2020-07-20 om 10 43 41](https://user-images.githubusercontent.com/1244416/87917891-ededf200-ca75-11ea-8305-c615a0ef0717.png)

![Schermafbeelding 2020-07-20 om 10 43 46](https://user-images.githubusercontent.com/1244416/87917901-f34b3c80-ca75-11ea-8c86-661c4983719d.png)
